[colors.cursor]
cursor = "0x808080"
text = "0xffffff"

[font]
size = 10

[font.offset]
x = 1
y = 8

[font.glyph_offset]
x = 0
y = 2

[font.normal]
family = "monaspicekr nerd font"
style = "regular"

[font.bold]
style = "regular"

[font.italic]
family = "monaspicern nerd font"
style = "italic"

[font.bold_italic]
family = "monaspicern nerd font"
style = "italic"

[terminal.shell]
program = "fish"

[window]
# opacity = 0.9
dynamic_padding = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[mouse]
# hide_when_typing = true

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/github_light_high_contrast.toml"
]

[terminal]
