# Managed by Home Manager because fish has a Nix store path on NixOS.
# set-option -g default-shell /usr/bin/fish
# set-option -g default-command /usr/bin/fish

# status bar
set -g status-position bottom
set -g status-style "bg=#3a454a,fg=#d8dee9"

# left session
set -g status-left "#[fg=#91aa96,bold] #S "

# right time
set -g status-right "#[fg=#d8dee9]%Y-%m-%d %H:%M "

# no-focused window
set -g window-status-format " #I:#W "
set -g window-status-style "fg=#a0a0a0"

# current window
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#607c66,fg=#ffffff,bold"

# pane
set -g pane-border-style "fg=#526b58"
set -g pane-active-border-style "fg=#91aa96"

# copy mode
set -g mode-style "bg=#e67e22,fg=#ffffff"

# message
set -g message-style "bg=#607c66,fg=#ffffff"

set -g mouse on

set -g mode-keys vi
set -g status-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
