# Managed by Home Manager because fish has a Nix store path on NixOS.
# set-option -g default-shell /usr/bin/fish
# set-option -g default-command /usr/bin/fish

# status bar
set -g status-position bottom
set -g status-style "bg=#24273a,fg=#cad3f5"

# left session
set -g status-left "#[fg=#8aadf4,bold] #S "

# right time
set -g status-right "#[fg=#a6da95]%Y-%m-%d %H:%M "

# no-focused window
set -g window-status-format " #I:#W "

# current window
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "bg=#8aadf4,fg=#24273a,bold"

# pane
set -g pane-border-style "fg=#494d64"
set -g pane-active-border-style "fg=#8aadf4"

# copy mode
set -g mode-style "bg=#f5a97f,fg=#24273a"

# message
set -g message-style "bg=#a6da95,fg=#24273a"

set -g mouse on

set -g mode-keys vi
set -g status-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
